
- name: Hello World
  hosts: local
  connection: local
  tasks:
  - name: printing Hello World
    ansible.builtin.debug:
      msg: "Hello World"

  - name: Priting Welcome to Ansible Practice Class
    ansible.builtin.debug:
      msg: "Welcome to Ansible Practice Class"