---
# - name: Variables Demo
#   hosts: servers

#   vars:
#     NAME: Siva

#   tasks:
#     - name: Print Variables
#       debug:
#         msg: "My name is {{ NAME }}"


- name: Self Intruduction
  hosts: servers


  vars:
    Name: Siva Ganesh Thota SL
    Skills: DevOps with AWS
    Company: Volvo

  tasks:
    - name: Print Self Intruduction
      debug:
        msg: "My name is {{ Name }}" 
  tasks:
    - name: Print Skills
      debug:
        msg: "My Skills are {{ SKILLS }}"

  tasks:
    - name: Print Company
      debug:
        msg: "My COMPANY IS {{ COMPANY }}"
        
      



