---

- name: Multiple Variables
  hosts: servers


  vars:
    NAME: Siva Ganesh Thota SL
    SKILLS: Devops With AWS
    COMPANY: Benz


  tasks:
    name: Printing Multiple Variables
    debug:
      msg: "My Name is {{ NAME }} Work as {{ SKILLS }} in {{ COMPANY }}"



