---

- name: Self Intruduction
  hosts: servers


  vars:
    Name: Siva Ganesh Thota SL
    Skills: DevOps with AWS
    Company: Volvo

  tasks:
    - name: Print Self Intruduction
      debug:
        msg: "My name is {{ Name }} work as {{ Skills }} in {{ Company }}"

