# Creating Files using ansible

- name: File Creation  # this is the name of playbook
  hosts: local
  connection: local

  tasks:
  - name: Creating a File
    ansible.builtin.file:
      path: /tmp/ansible.txt
      state: touch
  - name: Creating a file
    ansible.builtin.file:
      path: /tmp/ansible.txt1
      state: touch

      
  

      