---


- name: Register Variable example
  hosts: servers


  tasks: Check uptime
    - name: checking uptime
      command: uptime
      register: UPTIME
  
    - name: print the uptime
      debug:
        var: UPTIME.stdout
  

