---

- name: Register Variables example
  hosts: servers


  tasks:
    - name: check uptime
      command: uptime
      register: UPTIME_OUTPUT

    - name: Print uptime
      debug:
        var: UPTIME_OUTPUT.stdout


