---

- name: Register Variable example
  hosts: servers



  tasks:  
    - name: check uptime
      command: uptime
      register: UPTIME_OUTPUT


    - name: print uptime
      debug:
        var: UPTIME_OUTPUT.stdout 