---


- name: Disk Usage
  hosts: servers


  tasks:
    - name: Run df command
      command: df -h
      register: DISK

    - name: Printing disk Usage
      debug:
        var: DISK.stdout




    
