- name: vars files
  hosts: local
  connection: local

  vars_files:
  - couse.yaml
  
  tasks:
  - name: Print Course yaml details
    ansible.builtin.debug:
      msg: "Hello {{ Course}}, Course Duration is {{ Duration }}, Trainer is {{ Trainer }}"

      
