---


- name: Variables
  hosts: servers


  vars:
    NAME: Siva Ganesh Thota SL
    ROLE: Devops With AWS Engineer
    CITY: SINGAPORE



  tasks:
    - name: Printing Name
      debug:
        msg: "My Name is {{ NAME }}"

    - name: Printing Name
      debug:
        msg: "I am {{ ROLE }}"

    - name: Printing Company
      debug:
        msg: "I live in {{ CITY }}"