# Practice Task4
# Creating Directory using Dir module

- name: Directory Creation
  hosts: local
  connection: local

  tasks:
  - name: Creating  a Dir 
    ansible.builtin.file:   # this module also used to created dir as well.
      path: /opt/ansible_project
      state: directory

