- name: Variables from Prompt
  hosts: local
  connection: local

  vars_prompt:
  - name: username
    prompt: Please Enter Your username
    private: true

  - name: password
    prompt: Please Enter Your password
    private: true


  tasks:
  - name: Printing Username and password
    ansible.builtin.debug:
      msg: "Hello Username is {{ username }} Password is {{ password }}"


      




