- name: Variables from  prompt
  hosts: local
  connection: local
  
  vars_prompt:
  - name: username
    prompt: Please Enter Your username
    private: true

  - name: password
    prompt: Please Enter Your password
    private: true


  tasks:
  - name: Print username and password
    ansible.builtin.debug:
      msg: "Hello Username is {{ username }} and Password is {{ password }}"




