- name: Understand Variable preference
  hosts: local
  connection: local

  # vars:
  #   Greeting: "Hello From Play"

  # vars_files:
  # - course.yaml

  # vars_prompt:
  # - name: Greeting
  #   prompt: Please Enter the Greeting
  #   private: false

  tasks:
  - name: print the Greeting
    # vars:
    #   Greeting: "Hello From Task"
    ansible.builtin.debug:
      msg: "{{ Greeting }}"

# 1 command line or args
# 2 taks level arguments
# 3 File
# 4 Prompt
# 5 play level
# 6 inventory

