- name: Variable Datatypes
  hosts: local
  connection: local

  vars:
    Duration: 120 # this is Numaric Variable
    Course: DevSecOps With AWS # string Variable
    Is_Live: true  # boolean Variable
    Tools:
    - Linux
    - Shell
    - Ansible
    Concepts:     # Map or Dictonary or object. refered like {}
      CI: Jenkins
      SCRIPTING: "Shell, Ansible, Terraform, Python"

    tasks:
    - name: Printing Course Details
      ansible.builtin.debug:
        msg: "Hello {{ Course }}, Duration is {{ Duration }}, Is Live { Is_Live }, Concepts are {{ Concepts }}"