- name: Ansible Datatypes
  hosts: local
  connection: local


  vars:
    DURATION: 120 # Numeric Vars
    COURSE: DevSecOps With AWS # String Vars
    IS_LIVE: true  # boolean Vars
    TOOLS:   # List Vars
    - Linux
    - Shell
    - Ansible
    CONCEPTS:   # map or dictonary vars
      CI: Jenkins
      SCRIPTING: "Shell, Ansible, Terraform, Python"

  tasks:
  - name: Printing Course Details
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Duration is {{ DURATION }}, Is Live {{ IS_LIVE }}, Concepts are {{ CONCEPTS }}"



