- name: Conditions Demo
  hosts: local
  connection: local

  vars:
    NUMBER: 63
  tasks:
  - name: Print if the number is less than 100
    ansible.builtin.debug:
      msg: "Given Number {{ NUMBER }} is less than 100 "
    when: NUMBER < 100


  - name: Print if the number is greater than 100
    ansible.builtin.debug:
      msg: "Given Number {{ NUMBER }} is Greater than 100"
    when: NUMBER > 100

