# Variable Practice Task 1
# Create a Variable

- name: VAr creation
  hosts: local
  connection: local

  tasks:
  - name: creating a variable
    vars:
      CITY: Hyderabad

  - name: display the city 
    ansible.builtin.debug:
      msg: "i live in {{ CITY }}"

  

