- name: installing nginx package
  hosts: local
  connection: local

  vars:
    PACKAGE: nginx

  tasks: 
  - name: Displaying  Nginx PACKAGE
    ansible.builtin.debug:
      msg: "Installing {{ PACKAGE }}"
  
  - name: Installing Nginx
    ansible.builtin.package:
      name: {{ PACKAGE }}
      state: present
  - name: Displaying Installation Success
    ansible.builtin.debug:
      msg: "{{ PACKAGE }} IS Installed Successfully"




