---
# Create a user using var

- name: User var
  hosts: local
  connection: local
  become: true

  vars:
    USERNAME: siva
  
  tasks:
  - name: Create a user
    ansible.builtin.user:
      name: "{{ USERNAME }}"
      state: present

