---
# Accessing File variables

- name: File Varaibles Example
  hosts: local
  connection: local

  vars_file:
    - vars.yaml
  
  tasks:
  - name: Display Varaibles from var.yaml
    ansible.builtin.debug:
      msg:
        - "This is {{ NAME }}"
        - "I work in {{ COMPANY }}"
        - "I live in {{ CITY }}"
        