# Ask the user for a name and print given input by user

- name: Prompt Variable Demo
  hosts: local
  connection: local


  vars_prompt:  # this is used for read user input. in shell script we used read -p "prompt" <varname>
    name: USER_NAME
    prompt: Enter Your Name
    private: no  # whether inpurt is visible or not

  tasks:
  - name: Display the user prompt
    ansible.builtin.debug: 
      msg: "Welocome to Ansible Practice Class {{ USER_NAME }}. We are happy to have you here"



# What Did We Learn?
# Taking user input.
# Storing input in variables.
# Using input later.

