# Ask the user for a name and print given input by user

- name: Prompt Variable Demo
  hosts: local
  connection: local


  vars_prompt:
    name: USER_NAME
    prompt: Enter Your Name
    private: no

  tasks:
  - name: Display the user prompt
    ansible.builtin.debug: 
      msg: "Welocome to Ansible Practice Class : {{ USER_NAME }}. We are happy to have you here"

      

