# Hide Sensitive Information

- name: Password Prompt  # this is the name of playbook
  hosts: local # runs it in the local host
  connection: local

  vars_prompt:   # vars_prompt stops the playbook to ask the user for data at runtime
    - name: DB_USER
      prompt: Enter DB User Name
      private: no
      unsafe: false

    - name: DB_PASSWD
      prompt: Enter Your DB Password
      private: yes
      unsafe: false

  tasks:
  - name: Display Password Recieved Successfully
    ansible.builtin.debug:
      msg: "Password Recieved Successfully" # We are just printing the msg
      #msg: "{{ DB_PASSWD }} Password Recieved Successfully"  # if you want to see the password that is given by user you can access that DB_PASSWD.it's just for validate not for realtime practice.


# What Did We Learn?
# Use:
# private: yes
# for hiding passwords and sensitive data. 

  