# Multiple Command line Variables 

- name: Employee Details 
  hosts: local
  connection: local


  tasks:
  - name: Display Extra Varaibles or command line Variables
    ansible.builtin.debug:
      msg:
        - "This is {{ EMP_NAME }}"
        - "I Work as a {{ ROLE }} In {{ COMPANY }}"


        