# Installing packages

- name: Install Package
  hosts: local # we can install on different servers if needed.
  connection: local


  tasks:
  - name: Install Package
    ansible.builtin.package:
      name: "{{ PACKAGE }}"
      state: present
  - name: Display Success status  
    ansible.builtin.debug:
      msg: "{{ PACKAGE }} is installed Successfully"

# Install nginx
# ansible-playbook -i inventory.ini 37-realtime-extra-var.yaml -e "PACKAGE=nginx"

# Install Apache
# ansible-playbook -i inventory.ini 37-realtime-extra-var.yaml -e "PACKAGE=httpd"

# Install Mysql
# ansible-playbook -i inventory.ini 37-realtime-extra-var.yaml -e "PACKAGE=mysql"