# Check Which Variable type is considered as 1st

- name: Variable precedence
  hosts: local
  connection: local
  
  # 1st Command line vars or extra vars this should run while playbook execute
  # 2nd inventory vars added done
  # 3rd Play level Vars
  vars:
    NAME: PlayVars


  # 4th prompt level vars
  vars_prompt:
    name: NAME
    prompt: Enter Your Name
    private: no

  

  # 5th task level

  tasks:
  - name: task level Vars
    vars:
      NAME: Task Vars
    ansible.builtin.debug:
      msg: "{{ NAME }}"

  - name: display name
    ansible.builtin.debug:
      msg: "{{ NAME }}"
# first
# ansible-playbook -i inventory.ini 41-var-preference-check.yaml -e "NAME=Siva Ganesh Thota SL"
# first execution is success so first winner is Command line vars

# Second
# ansible-playbook -i inventory.ini 41-var-preference-check.yaml
# Second Execution is success while we ran we got prompt once we given got the task level vars results
# so Second winner is Task level


