# Display Specific Facts
# Hostname

- name: Hostname Ansible Facts Demo
  hosts: local
  connection: local

  tasks:
  - name: Display hostname Facts
    ansible.builtin.debug:
      msg: "ansible_hostname"


  