# Display Specific Facts
# Hostname

- name: Hostname Ansible Facts Demo
  hosts: local
  connection: local

  tasks:
  - name: Display hostname Facts
    ansible.builtin.debug:
      var: "ansible_hostname"


# Rules to Remember
# var: ansible_hostname --> print variable value directly 
# msg: "ansible_hostname" --> Print plain text
# msg: "{{ ansible_hostname }}" --> Print variable value inside a message






  