# Display hostname, distribution, and ipv4 address

- name: Display Hostname, distribution, ipv4
  hosts: local
  connection: local


  tasks:
  - name: Display facts
    ansible.builtin.debug:
      msg:     # to list all the facts we use msg: instead var: here we used {{ }} brases to access the facts.
        - "{{ ansible_hostname }}"
        - "{{ ansible_distribution }}"
        - "{{ ansible_default_ipv4.address }}"
