# Simple Variable Condition

- name: Condition Variable
  hosts: local
  connection: local

  vars:
    ENV: QA 

  tasks:
  - name: Production Deployment
    ansible.builtin.debug:
      msg: "Deploying Application"
    when: ENV == "Prod"
