# skipp root user

- name: Skipp Root User
  hosts: local
  connection: local
  become: true
  vars:
    USERNAME: ec2-user

  tasks:
  - name: Normal user log in
    ansible.builtin.debug:
      msg:  "User Allowed"
    when: USERNAME != "root"