# # Check Uptime using register var

- name: Register Example
  hosts: local
  connection: local


  tasks:
  - name: check Uptime
    ansible.builtin.command: uptime
    register: UPTIME_OUTPUT
  - name: Display the output
    ansible.builtin.debug:
      var: "UPTIME_OUTPUT.stdout"