# Create Multiple file using loop

- name: Multi files
  hosts: local
  connection: local


  tasks:
  - name: Create files
    ansible.builtin.file:
      path: /tmp/{{ item }}
      state: touch
    loop:
      - app.log
      - web.log
      - db.log
      