# Create Multiple file using loop

- name: Multi files
  hosts: local
  connection: local


  tasks:
  - name: Create files
    ansible.builtin.file:  # this mudule is used to create file
      path: /tmp/{{ item }}  # item is used to take values one by one from loop:
      state: touch
    loop:
      - app.log
      - web.log
      - db.log
