# loop variable

- name: Create users
  hosts: local
  connection: local
  become: true

  vars:
    USERS:
      - devuser
      - testuser
      - appuser

  tasks:
  - name: Creating users
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
    loop: "{{ USERS }}"