# Redirect Output

- name: Redirect Output using command
  hosts: local
  connection: local

  tasks:
  - name: Redirect output
    ansible.builtin.command: "date > /tmp/date/.txt"

  - name: Redirect output
    ansible.builtin.shell: "date > /tmp/date/.txt"









