# Environment Variables

- name: Env var
  hosts: local
  connection: local

  tasks:
  - name: check env var
    ansible.builtin.command: "echo $HOME"

  - name: Check in shell
    ansible.builtin.shell: "echo $HOME"