- name: Array Varaibles Demo  # this is the name of playbook
  hosts: local   # run in the local host
  connection: local


  vars:  # Array Variables
    PACKAGES: # List Array Variables
    - nginx
    - Git
    - Docker
    - Jenkins
    - MongoDB


  tasks:
  - name: Print First package 
    ansible.builtin.debug:
      msg: "Installing First {{ PACKAGES[0] }}"
      

