- name: Display all the PACKAGES # this is name of playbook
  hosts: local  # runs in the localhost
  connection: local


  vars:
    PACKAGES:  # this is list variables
    - nginx
    - Docker
    - Git
    - MongoDB


  tasks:
  - name: Display the PACKAGES list
    ansible.builtin.debug:
      msg: "Installing packages are {{ PACKAGES }}"
      