---


- name: Register Hostname Variable
  hosts: servers


  tasks:
    - name: Hostname
      command: hostname
      register: HOSTNAME_OUTPUT

    - name: printing Hostname
      debug:
        var: HOSTNAME_OUTPUT.stdout




  