[servers]
172.31.24.238 SERVER_ROLE=WEB
172.31.25.92 SERVER_ROLE=WEB




[local]
localhost

; Group Variables
; [local:vars]
; Course=Variables
; Duration=1.5HR
; Trainer=Siva Ganesh Thota SL
; Greeting=Hello From Inventory