[servers]
54.89.203.203 SERVER_ROLE=WEB ansible_user=ec2-user ansible_password=DevOps321
3.91.76.198 SERVER_ROLE=WEB ansible_user=ec2-user ansible_password=DevOps321

[servers:vars]
PACKAGE: httpd
PORT: 80



[local]
localhost

; Group Variables
; [local:vars]
; Course=Variables
; Duration=1.5HR
; Trainer=Siva Ganesh Thota SL
; Greeting=Hello From Inventory