---


- name: package list
  hosts: servers

  vars:
    PACKAGE:
      - nginx
      - git
      - dockers
      - mysql

  tasks:
    - name: printing package list
      debug:
        msg: "{{PACKAGE[0]}}"

    - name:
      debug:
        msg: "{{PACKAGE[1]}}"

    - name:
      debug:
        msg: "{{PACKAGE[2]}}"




# ---

# - name: Package list
#   hosts: servers


#   vars:
#     PACKAGES:
#       - nginx
#       - git
#       - mysql


#   tasks:
#     - name: Printing Packages list
#       debug:
#         msg: "{{PACKAGES}}"