- name: Check Free Memory
  hosts: local
  connection: local


  tasks:
  - name: Register Command
    command: free -h
    register: MEMORY_OUTPUT

  - name: Display the Output
    ansible.builtin.debug:
      var: MEMORY_OUTPUT.stdout

      