- name: register Varaible Demo
  hosts: local
  connection: local

  tasks:
  - name: Check Uptime
    command: Uptime
    register: UPTIME_OUTPUT

  - name: Display Uptime
    ansible.builtin.debug:
      var: UPTIME_OUTPUT.stdout



