---
- name: Register Example
  hosts: local
  connection: local

  tasks:

  - name: Check uptime
    command: uptime
    register: UPTIME_OUTPUT

  - name: Print uptime
    debug:
      var: UPTIME_OUTPUT.stdout


