---


- name: check uptime
  hosts: servers


  tasks:
    - name: checking uptime
      command: uptime
      register: UPTIME_OUTPUT


    - name: printing uptime
      debug:
        var: UPTIME_OUTPUT.stdout

        