- name: Register command output in Variable # This is the name of playbook
  hosts: local  # Runs in the localhost
  connection: local

  tasks:
  - name: Check Uptime
    command: Uptime
    register: UPTIME_OUTPUT

  - name: Display Uptime
    ansible.builtin.debug:
      var: UPTIME_OUTPUT.stdout

      

