- name: Datatypes Variables  # this is the name of the playbook
  hosts: local # run in the localhost
  connection: local

  vars: # Datatypes variables
    NAME: Siva Ganesh Thota # this is String Variable
    AGE: 30   # this is Number or Numeric Variable
    IS_ADMIN: true   # this boolean Variable
    PACKAGES:  # This is List Varaibles
    - nginx
    - Git 
    - Docker
    - mysql
    CONCEPTS:   # Map or Dictionary Variables
      CI: Jenkins
      SCRIPTING: "Shell, Ansible, Terraform, Python"

  tasks:
  - name: Print Datatypes Varaibles
    ansible.builtin.debug:
      msg: "This is {{ NAME }}, I am {{ AGE }} Years Old, Is Admin {{ IS_ADMIN }}, PACKAGES are {{ PACKAGES }}, CONCEPTS are {{ CONCEPTS }}"

